---
exclude: ['README.markdown']
permalink: ':title'
pygments: true
safe: false
title: 'Carte'
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/"
url:            "https://github.com/monaq/gitpage-test.github.io.git"